version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: rac
      POSTGRES_PASSWORD: javatest
      POSTGRES_DB: fullstackdb
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://rac:javatest@db:5432/fullstackdb

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
